name: Build and Deploy Binary

on:
  push:
    branches:
      - improve-performance

jobs:
  build:
    # Prevent running the job if the commit message contains "[skip ci]"
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build Release Binary
        run: cargo build --release --manifest-path cli/Cargo.toml

      - name: Copy binary to target folder
        run: |
          mkdir -p bin/linux
          cp target/release/trabas bin/linux/

      - name: Commit built binary
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add bin/linux/trabas
          git commit -m "Binary updated [skip ci]"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/amirkode/trabas.git HEAD:improve-performance
