name: Build Binary

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Extract Version from Cargo.toml
        id: get_version
        shell: bash
        run: echo "VERSION=$(cargo metadata --format-version 1 --no-deps | jq -r '.packages[] | select(.name=="trabas") | .version')" >> $GITHUB_ENV

      - name: Build Release Binary
        run: cargo build --release --manifest-path cli/Cargo.toml

      - name: Upload Artifact (Linux)
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: trabas-${{ env.VERSION }}-linux
          path: target/release/trabas

      - name: Upload Artifact (Windows)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: trabas-${{ env.VERSION }}-windows
          path: target/release/trabas.exe

      - name: Upload Artifact (macOS)
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: trabas-${{ env.VERSION }}-macos
          path: target/release/trabas
