# based on template
name: Try Build and Run Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  common-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run e2e tests
      run: cargo test --verbose -- --test-threads=1 --nocapture
    - name: Run "common" package tests
      run: cargo test --package common --verbose -- --test-threads=1 --nocapture

  # TODO: simulate integration tests, e.g. run a server with redis